// components/ui/Hero.tsx
import { cn } from '../../lib/helpers'

interface HeroProps {
  className?: string
  title?: string
  description?: string
}

const css = {
  section: 'mb-10 sm:mb-12 md:mb-14 lg:mb-16',
  inner: 'mb-3 py-10 sm:py-12 md:py-14 lg:py-16 max-w-5xl mx-auto px-4 text-center',
  title: 'text-4xl sm:text-6xl inline-flex font-semibold tracking-tight',
  description: 'text-sm sm:text-base md:text-lg mt-2 sm:mt-3 max-w-2xl mx-auto',
}

export default function Hero({ className, title, description }: HeroProps) {
  return (
    <section className={cn(css.section, className)}>
      <div className={css.inner}>
        <h1 className={css.title}>{title}</h1>
        {description && <p className={css.description}>{description}</p>}
      </div>
    </section>
  )
}

// src/routes/contact/Hero.svelte
<script lang="ts">
	const css = {
		wrapper: 'under-header h-screen max-h-[1000px]', // bg-cream
		inner: 'max-w-7xl mx-auto px-4',
		title: 'flex flex-col text-8xl font-medium tracking-tight'
	}
</script>

<section class={css.wrapper}>
	<div class={css.inner}>
		<h1 class={css.title}>Contact</h1>
	</div>
</section>
