// components/header/Burger.tsx
import { cn } from '../../lib/helpers'
import { __ } from '../../lib/translate'
import useStore from '../../lib/store'

const css = {
  wrapper:
    'md:hidden inline-flex justify-center items-center h-11 w-11 rounded-full hover:bg-black/5 dark:hover:bg-white/5',
  lines: 'w-6 h-6 space-y-1.5 flex flex-col items-center justify-center',
  line: 'bg-black dark:bg-white w-full h-[2px] origin-center duration-[150ms] transition-[transform]',
  lineTop: 'rotate-45 translate-y-1',
  lineBottom: '-rotate-45 -translate-y-1',
}

export default function Burger() {
  const isMenuOpen = useStore((state) => state.isMenuOpen)
  const toggleMenu = useStore((state) => state.toggleMenu)

  return (
    <button className={css.wrapper} onClick={toggleMenu} aria-label={__('toggleNav')}>
      <span className={css.lines}>
        <span className={cn(css.line, isMenuOpen && css.lineTop)} />
        <span className={cn(css.line, isMenuOpen && css.lineBottom)} />
      </span>
    </button>
  )
}

// src/components/header/Burger.svelte
<script>
	import { offCanvas } from '$lib/stores/offCanvas'
	import { clickOutside } from '$lib/directives/clickOutside'
	import { cn } from '$lib/utils/helpers'
	import Magnetic from '../Magnetic.svelte'
	import OffCanvas from './OffCanvas.svelte'

	const { toggle, hide } = offCanvas
	const css = {
		magnetic: 'z-50 in-flex centered fixed top-4 right-4 sm:top-5 sm:right-5 md:top-6 md:right-6',
		btn: 'in-flex flex-col centered sq-14 sm:sq-16 md:sq-20 rounded-full text-white transition-all',
		default: 'bg-footer hover:bg-blue-600 gap-2 hover:gap-3',
		active: 'bg-blue-600 gap-4',
		line: 'w-6 h-px bg-white in-flex transition-all duration-300 origin-right',
		activeLine: 'first:-rotate-45 last:rotate-45 -translate-x-1'
	}
</script>

<div use:clickOutside on:outclick={hide}>
	<Magnetic class={css.magnetic} power={50}>
		<button class={cn(css.btn, $offCanvas ? css.active : css.default)} on:click={toggle}>
			<div class={cn(css.line, $offCanvas && css.activeLine)} />
			<div class={cn(css.line, $offCanvas && css.activeLine)} />
		</button>
	</Magnetic>
	<OffCanvas />
</div>
